// src/components/chat/ChatMessage.tsx

"use client";

import { Message } from "@/types/chat";

interface ChatMessageProps {
  message: Message;
  }

  function formatContent(content: string): React.ReactNode {
    const lines = content.split("\n");

      return lines.map((line, index) => {
          // --- Heading: lines starting with ** on both ends ---
              if (line.startsWith("**") && line.endsWith("**") && line.length > 4) {
                    return (
                            <p key={index} className="font-semibold text-gray-900 mt-3 mb-1">
                                      {line.replace(/\*\*/g, "")}
                                              </p>
                                                    );
                                                        }

                                                            // --- Numbered list item ---
                                                                if (/^\d+\.\s/.test(line)) {
                                                                      return (
                                                                              <p key={index} className="flex gap-2 my-1">
                                                                                        <span className="font-semibold text-violet-600 shrink-0">
                                                                                                    {line.match(/^\d+\./)?.[0]}
                                                                                                              </span>
                                                                                                                        <span>{line.replace(/^\d+\.\s/, "")}</span>
                                                                                                                                </p>
                                                                                                                                      );
                                                                                                                                          }

                                                                                                                                              // --- Bullet list item ---
                                                                                                                                                  if (line.startsWith("- ") || line.startsWith("• ")) {
                                                                                                                                                        return (
                                                                                                                                                                <p key={index} className="flex gap-2 my-1">
                                                                                                                                                                          <span className="text-violet-400 shrink-0 mt-0.5">•</span>
                                                                                                                                                                                    <span>{line.replace(/^[-•]\s/, "")}</span>
                                                                                                                                                                                            </p>
                                                                                                                                                                                                  );
                                                                                                                                                                                                      }

                                                                                                                                                                                                          // --- Bold inline text: **text** ---
                                                                                                                                                                                                              if (line.includes("**")) {
                                                                                                                                                                                                                    const parts = line.split(/(\*\*[^*]+\*\*)/g);
                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                  <p key={index} className="my-1">
                                                                                                                                                                                                                                            {parts.map((part, i) =>
                                                                                                                                                                                                                                                        part.startsWith("**") && part.endsWith("**") ? (
                                                                                                                                                                                                                                                                      <strong key={i} className="font-semibold text-gray-900">
                                                                                                                                                                                                                                                                                      {part.replace(/\*\*/g, "")}
                                                                                                                                                                                                                                                                                                    </strong>
                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                              <span key={i}>{part}</span>
                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                          // --- Empty line: spacer ---
                                                                                                                                                                                                                                                                                                                                                                              if (line.trim() === "") {
                                                                                                                                                                                                                                                                                                                                                                                    return <div key={index} className="h-1" />;
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                            // --- Default paragraph ---
                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                      <p key={index} className="my-1 leading-relaxed">
                                                                                                                                                                                                                                                                                                                                                                                                              {line}
                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                          export default function ChatMessage({ message }: ChatMessageProps) {
                                                                                                                                                                                                                                                                                                                                                                                                                            const isUser = message.role === "user";

                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                        className={`flex w-full mb-4 ${isUser ? "justify-end" : "justify-start"}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* --- Assistant avatar --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {!isUser && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="shrink-0 w-8 h-8 rounded-full bg-violet-600 flex items-center justify-center text-white text-xs font-bold mr-3 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          N
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* --- Message bubble --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      max-w-[75%] px-4 py-3 rounded-2xl text-sm
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            isUser
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? "bg-violet-600 text-white rounded-tr-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : "bg-white border border-gray-200 text-gray-800 rounded-tl-sm shadow-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {isUser ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="leading-relaxed whitespace-pre-wrap">{message.content}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-0.5">{formatContent(message.content)}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* --- Timestamp --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className={`text-xs mt-2 ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  isUser ? "text-violet-200 text-right" : "text-gray-400"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {new Date(message.createdAt).toLocaleTimeString([], {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          hour: "2-digit",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      minute: "2-digit",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* --- User avatar --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {isUser && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="shrink-0 w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center text-gray-600 text-xs font-bold ml-3 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            U
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }