// src/components/chat/ChatInput.tsx

"use client";

import { useState, useRef, useEffect } from "react";
import { Mode } from "@/types/chat";

interface ChatInputProps {
  onSend: (content: string) => void;
    isLoading: boolean;
      mode: Mode;
        disabled?: boolean;
        }

        const PLACEHOLDERS: Record<Mode, string> = {
          study: "Ask me anything about your studies...",
            career: "Ask me about your career, skills, or resume...",
            };

            const MAX_ROWS = 6;
            const MIN_ROWS = 1;

            export default function ChatInput({
              onSend,
                isLoading,
                  mode,
                    disabled = false,
                    }: ChatInputProps) {
                      const [value, setValue] = useState("");
                        const textareaRef = useRef<HTMLTextAreaElement>(null);

                          // --- Auto-resize textarea height based on content ---
                            useEffect(() => {
                                const textarea = textareaRef.current;
                                    if (!textarea) return;

                                        textarea.style.height = "auto";
                                            const lineHeight = 24;
                                                const maxHeight = lineHeight * MAX_ROWS;
                                                    const minHeight = lineHeight * MIN_ROWS;

                                                        textarea.style.height = `${Math.min(
                                                              Math.max(textarea.scrollHeight, minHeight),
                                                                    maxHeight
                                                                        )}px`;
                                                                          }, [value]);

                                                                            // --- Focus input on mount ---
                                                                              useEffect(() => {
                                                                                  if (!disabled) {
                                                                                        textareaRef.current?.focus();
                                                                                            }
                                                                                              }, [disabled]);

                                                                                                const canSend = value.trim().length > 0 && !isLoading && !disabled;

                                                                                                  function handleSend() {
                                                                                                      if (!canSend) return;
                                                                                                          onSend(value.trim());
                                                                                                              setValue("");

                                                                                                                  // Reset textarea height after send
                                                                                                                      if (textareaRef.current) {
                                                                                                                            textareaRef.current.style.height = "auto";
                                                                                                                                }
                                                                                                                                  }

                                                                                                                                    function handleKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
                                                                                                                                        // Send on Enter, new line on Shift+Enter
                                                                                                                                            if (e.key === "Enter" && !e.shiftKey) {
                                                                                                                                                  e.preventDefault();
                                                                                                                                                        handleSend();
                                                                                                                                                            }
                                                                                                                                                              }

                                                                                                                                                                return (
                                                                                                                                                                    <div className="w-full px-4 py-4 bg-white border-t border-gray-100">
                                                                                                                                                                          <div className="max-w-3xl mx-auto w-full">
                                                                                                                                                                                  <div
                                                                                                                                                                                            className={`
                                                                                                                                                                                                        flex items-end gap-3 px-4 py-3 rounded-2xl border
                                                                                                                                                                                                                    transition-all duration-200
                                                                                                                                                                                                                                ${
                                                                                                                                                                                                                                              disabled
                                                                                                                                                                                                                                                              ? "bg-gray-50 border-gray-200"
                                                                                                                                                                                                                                                                              : "bg-white border-gray-300 focus-within:border-violet-500 focus-within:shadow-sm focus-within:shadow-violet-100"
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                    `}
                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                      {/* --- Textarea --- */}
                                                                                                                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                                                                                                                            ref={textareaRef}
                                                                                                                                                                                                                                                                                                                                                        value={value}
                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setValue(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                onKeyDown={handleKeyDown}
                                                                                                                                                                                                                                                                                                                                                                                            placeholder={PLACEHOLDERS[mode]}
                                                                                                                                                                                                                                                                                                                                                                                                        disabled={isLoading || disabled}
                                                                                                                                                                                                                                                                                                                                                                                                                    rows={MIN_ROWS}
                                                                                                                                                                                                                                                                                                                                                                                                                                className={`
                                                                                                                                                                                                                                                                                                                                                                                                                                              flex-1 resize-none bg-transparent text-sm text-gray-800
                                                                                                                                                                                                                                                                                                                                                                                                                                                            placeholder:text-gray-400 focus:outline-none leading-6
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled:cursor-not-allowed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      `}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* --- Send button --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleSend}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={!canSend}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        aria-label="Send message"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className={`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  shrink-0 w-9 h-9 rounded-xl flex items-center justify-center
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transition-all duration-200 focus:outline-none
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              focus-visible:ring-2 focus-visible:ring-violet-500
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            canSend
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ? "bg-violet-600 hover:bg-violet-700 text-white shadow-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : "bg-gray-100 text-gray-400 cursor-not-allowed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {isLoading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Loading spinner
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <svg
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-4 h-4 animate-spin"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fill="none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            viewBox="0 0 24 24"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <circle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="opacity-25"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cx="12"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cy="12"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  r="10"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    stroke="currentColor"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      strokeWidth="4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="opacity-75"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fill="currentColor"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            d="M4 12a8 8 0 018-8v8z"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Send arrow icon
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <svg
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-4 h-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fill="none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  stroke="currentColor"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  strokeWidth={2.5}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  viewBox="0 0 24 24"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  strokeLinecap="round"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    strokeLinejoin="round"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* --- Helper text --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-gray-400 text-center mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Press{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <kbd className="px-1 py-0.5 bg-gray-100 rounded text-gray-500 font-mono text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Enter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </kbd>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      to send,{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <kbd className="px-1 py-0.5 bg-gray-100 rounded text-gray-500 font-mono text-xs">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Shift + Enter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </kbd>{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for a new line
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }