// src/components/chat/ChatWindow.tsx

"use client";

import { useEffect, useRef } from "react";
import { Message } from "@/types/chat";
import ChatMessage from "@/components/chat/ChatMessage";

interface ChatWindowProps {
  messages: Message[];
    isLoading: boolean;
    }

    function TypingIndicator() {
      return (
          <div className="flex w-full mb-4 justify-start">
                {/* Avatar */}
                      <div className="shrink-0 w-8 h-8 rounded-full bg-violet-600 flex items-center justify-center text-white text-xs font-bold mr-3 mt-1">
                              N
                                    </div>

                                          {/* Animated dots */}
                                                <div className="bg-white border border-gray-200 shadow-sm px-4 py-3 rounded-2xl rounded-tl-sm flex items-center gap-1.5">
                                                        <span
                                                                  className="w-2 h-2 rounded-full bg-violet-400 animate-bounce"
                                                                            style={{ animationDelay: "0ms" }}
                                                                                    />
                                                                                            <span
                                                                                                      className="w-2 h-2 rounded-full bg-violet-400 animate-bounce"
                                                                                                                style={{ animationDelay: "150ms" }}
                                                                                                                        />
                                                                                                                                <span
                                                                                                                                          className="w-2 h-2 rounded-full bg-violet-400 animate-bounce"
                                                                                                                                                    style={{ animationDelay: "300ms" }}
                                                                                                                                                            />
                                                                                                                                                                  </div>
                                                                                                                                                                      </div>
                                                                                                                                                                        );
                                                                                                                                                                        }

                                                                                                                                                                        function EmptyState() {
                                                                                                                                                                          return (
                                                                                                                                                                              <div className="flex flex-col items-center justify-center h-full text-center px-6">
                                                                                                                                                                                    <div className="w-14 h-14 rounded-full bg-violet-100 flex items-center justify-center mb-4">
                                                                                                                                                                                            <span className="text-2xl">✨</span>
                                                                                                                                                                                                  </div>
                                                                                                                                                                                                        <h2 className="text-lg font-semibold text-gray-800 mb-2">
                                                                                                                                                                                                                Welcome to NIRA AI
                                                                                                                                                                                                                      </h2>
                                                                                                                                                                                                                            <p className="text-sm text-gray-500 max-w-xs leading-relaxed">
                                                                                                                                                                                                                                    Select a mode above and start a conversation. Ask anything about your
                                                                                                                                                                                                                                            studies or career goals.
                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                        export default function ChatWindow({ messages, isLoading }: ChatWindowProps) {
                                                                                                                                                                                                                                                          const bottomRef = useRef<HTMLDivElement>(null);
                                                                                                                                                                                                                                                            const containerRef = useRef<HTMLDivElement>(null);

                                                                                                                                                                                                                                                              // --- Auto-scroll to bottom on new messages or loading state change ---
                                                                                                                                                                                                                                                                useEffect(() => {
                                                                                                                                                                                                                                                                    if (bottomRef.current) {
                                                                                                                                                                                                                                                                          bottomRef.current.scrollIntoView({ behavior: "smooth" });
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                }, [messages, isLoading]);

                                                                                                                                                                                                                                                                                  const hasMessages = messages.length > 0;

                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                              ref={containerRef}
                                                                                                                                                                                                                                                                                                    className="flex-1 overflow-y-auto px-4 py-6 scroll-smooth"
                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                              {/* --- Empty state --- */}
                                                                                                                                                                                                                                                                                                                    {!hasMessages && !isLoading && <EmptyState />}

                                                                                                                                                                                                                                                                                                                          {/* --- Message list --- */}
                                                                                                                                                                                                                                                                                                                                {hasMessages && (
                                                                                                                                                                                                                                                                                                                                        <div className="max-w-3xl mx-auto w-full">
                                                                                                                                                                                                                                                                                                                                                  {messages
                                                                                                                                                                                                                                                                                                                                                              .filter((m) => m.role !== "system")
                                                                                                                                                                                                                                                                                                                                                                          .map((message) => (
                                                                                                                                                                                                                                                                                                                                                                                        <ChatMessage key={message.id} message={message} />
                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                        {/* --- Typing indicator --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                              {isLoading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="max-w-3xl mx-auto w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                <TypingIndicator />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* --- Scroll anchor --- */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div ref={bottomRef} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }