// src/lib/basic/careerKnowledge/careerProfiles.ts

export type EntryDifficulty = "beginner" | "intermediate" | "advanced";
export type IncomePotential = "low" | "medium" | "high" | "very_high";
export type AfricaDemand = "low" | "growing" | "high" | "very_high";
export type StartupCost = "free" | "low" | "medium" | "high";

export interface CareerProfile {
  id: string;
  title: string;
  category: string;
  entryDifficulty: EntryDifficulty;
  startupCost: StartupCost;
  remoteFriendly: boolean;
  africaDemand: AfricaDemand;
  incomePotential: IncomePotential;
  requiresLaptop: boolean;
  requiresInternet: boolean;
  requiresPhysicalPresence: boolean;
  beginnerFriendly: boolean;
  timeToFirstIncome: string;
  keywords: string[];
  suitableFor: string[];
}

export const careerProfiles: CareerProfile[] = [
  {
    id: "freelancing",
    title: "Freelancing",
    category: "Business",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–4 weeks",
    keywords: ["freelancing", "self-employment", "gig work", "client work"],
    suitableFor: ["anyone with a marketable skill", "introverts", "people wanting flexibility"],
  },
  {
    id: "web_developer",
    title: "Web Developer",
    category: "Technology",
    entryDifficulty: "intermediate",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "4–8 months",
    keywords: ["coding", "programming", "websites", "apps", "technology"],
    suitableFor: ["analytical thinkers", "problem-solvers", "people who like building things"],
  },
  {
    id: "ui_ux_designer",
    title: "UI/UX Designer",
    category: "Design",
    entryDifficulty: "intermediate",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "3–6 months",
    keywords: ["design", "figma", "user experience", "products", "apps"],
    suitableFor: ["creative people", "visual thinkers", "empathetic people"],
  },
  {
    id: "data_analyst",
    title: "Data Analyst",
    category: "Technology",
    entryDifficulty: "intermediate",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "4–8 months",
    keywords: ["data", "excel", "sql", "analytics", "numbers", "insights"],
    suitableFor: ["analytical people", "detail-oriented", "curious about patterns"],
  },
  {
    id: "graphic_designer",
    title: "Graphic Designer",
    category: "Design",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "medium",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–3 months",
    keywords: ["design", "logos", "canva", "branding", "visual", "creative"],
    suitableFor: ["creative people", "visual thinkers", "art lovers"],
  },
  {
    id: "content_creator",
    title: "Content Creator",
    category: "Media",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "3–12 months",
    keywords: ["youtube", "tiktok", "social media", "videos", "audience", "creator"],
    suitableFor: ["extroverts", "storytellers", "people with passion niches"],
  },
  {
    id: "virtual_assistant",
    title: "Virtual Assistant",
    category: "Business Services",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "medium",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–2 weeks",
    keywords: ["admin", "assistant", "organization", "email", "calendar", "remote"],
    suitableFor: ["organized people", "good communicators", "beginners in remote work"],
  },
  {
    id: "social_media_manager",
    title: "Social Media Manager",
    category: "Marketing",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "medium",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "2–6 weeks",
    keywords: ["instagram", "facebook", "twitter", "content", "marketing", "social"],
    suitableFor: ["social people", "creative writers", "marketing enthusiasts"],
  },
  {
    id: "electrician",
    title: "Electrician",
    category: "Trades",
    entryDifficulty: "intermediate",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "6–18 months",
    keywords: ["electrical", "wiring", "installation", "maintenance", "solar", "trades"],
    suitableFor: ["hands-on people", "technical minds", "people without laptop access"],
  },
  {
    id: "video_editor",
    title: "Video Editor",
    category: "Media",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "medium",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–3 months",
    keywords: ["video", "editing", "youtube", "content", "films", "capcut", "davinci"],
    suitableFor: ["creative people", "film lovers", "detail-oriented"],
  },
  {
    id: "copywriter",
    title: "Copywriter",
    category: "Writing",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–3 months",
    keywords: ["writing", "sales", "ads", "email", "persuasion", "words"],
    suitableFor: ["strong writers", "persuasive people", "marketing lovers"],
  },
  {
    id: "software_developer",
    title: "Software Developer",
    category: "Technology",
    entryDifficulty: "advanced",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "6–12 months",
    keywords: ["programming", "coding", "software", "apps", "systems", "engineering"],
    suitableFor: ["logical thinkers", "problem-solvers", "patient learners"],
  },
  {
    id: "digital_marketer",
    title: "Digital Marketer",
    category: "Marketing",
    entryDifficulty: "beginner",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–3 months",
    keywords: ["marketing", "ads", "google", "meta", "facebook", "seo", "campaigns"],
    suitableFor: ["business-minded people", "data lovers", "creative strategists"],
  },
  {
    id: "data_scientist",
    title: "Data Scientist",
    category: "Technology",
    entryDifficulty: "advanced",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "8–18 months",
    keywords: ["data", "machine learning", "python", "statistics", "ai", "models"],
    suitableFor: ["mathematics lovers", "researchers", "analytical thinkers"],
  },
  {
    id: "cybersecurity_analyst",
    title: "Cybersecurity Analyst",
    category: "Technology",
    entryDifficulty: "advanced",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "8–18 months",
    keywords: ["security", "hacking", "network", "cyber", "protection", "linux"],
    suitableFor: ["curious and detail-oriented people", "problem-solvers", "tech enthusiasts"],
  },
  {
    id: "cloud_engineer",
    title: "Cloud Engineer",
    category: "Technology",
    entryDifficulty: "advanced",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "8–15 months",
    keywords: ["aws", "azure", "devops", "cloud", "infrastructure", "servers"],
    suitableFor: ["systematic thinkers", "existing IT professionals", "infrastructure-minded people"],
  },
  {
    id: "product_manager",
    title: "Product Manager",
    category: "Technology",
    entryDifficulty: "advanced",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "6–18 months",
    keywords: ["product", "roadmap", "strategy", "user research", "tech management"],
    suitableFor: ["business and tech cross-overs", "strategic thinkers", "communicators"],
  },
  {
    id: "photographer",
    title: "Photographer",
    category: "Creative",
    entryDifficulty: "beginner",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "high",
    incomePotential: "medium",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: true,
    timeToFirstIncome: "1–3 months",
    keywords: ["photos", "camera", "weddings", "events", "portrait", "visual"],
    suitableFor: ["visual creatives", "extroverts", "event lovers"],
  },
  {
    id: "teacher_tutor",
    title: "Teacher / Tutor",
    category: "Education",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "medium",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–2 weeks",
    keywords: ["teaching", "education", "tutoring", "students", "school", "lessons"],
    suitableFor: ["patient people", "subject matter experts", "educators"],
  },
  {
    id: "accountant",
    title: "Accountant",
    category: "Finance",
    entryDifficulty: "intermediate",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "2–5 years",
    keywords: ["finance", "numbers", "tax", "bookkeeping", "audit", "accounting"],
    suitableFor: ["detail-oriented people", "mathematically inclined", "structured thinkers"],
  },
  {
    id: "mobile_app_developer",
    title: "Mobile App Developer",
    category: "Technology",
    entryDifficulty: "intermediate",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "4–8 months",
    keywords: ["app", "flutter", "react native", "android", "ios", "mobile"],
    suitableFor: ["coders", "startup founders", "problem-solvers"],
  },
  {
    id: "seo_specialist",
    title: "SEO Specialist",
    category: "Marketing",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "medium",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "2–4 months",
    keywords: ["seo", "google", "ranking", "traffic", "search", "content strategy"],
    suitableFor: ["analytical writers", "patient people", "data-driven marketers"],
  },
  {
    id: "ecommerce_entrepreneur",
    title: "E-commerce Entrepreneur",
    category: "Business",
    entryDifficulty: "beginner",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–4 weeks",
    keywords: ["selling", "shop", "products", "online store", "business", "trade"],
    suitableFor: ["entrepreneurial people", "salespeople", "traders"],
  },
  {
    id: "hr_manager",
    title: "Human Resources Manager",
    category: "Management",
    entryDifficulty: "intermediate",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "6–18 months",
    keywords: ["people", "hiring", "recruitment", "culture", "hr", "talent"],
    suitableFor: ["empathetic people", "good communicators", "people lovers"],
  },
  {
    id: "financial_advisor",
    title: "Financial Advisor",
    category: "Finance",
    entryDifficulty: "advanced",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "12–24 months",
    keywords: ["investment", "money", "wealth", "savings", "finance", "planning"],
    suitableFor: ["finance enthusiasts", "trustworthy communicators", "planners"],
  },
  {
    id: "backend_developer",
    title: "Backend Developer",
    category: "Technology",
    entryDifficulty: "advanced",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "6–12 months",
    keywords: ["server", "api", "database", "node", "python", "backend", "infrastructure"],
    suitableFor: ["logical thinkers", "systems people", "infrastructure-minded"],
  },
  {
    id: "animator",
    title: "Animator",
    category: "Creative",
    entryDifficulty: "intermediate",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "4–9 months",
    keywords: ["animation", "blender", "motion", "film", "creative", "3d"],
    suitableFor: ["artists", "storytellers", "patient creatives"],
  },
  {
    id: "technical_writer",
    title: "Technical Writer",
    category: "Writing",
    entryDifficulty: "intermediate",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "2–5 months",
    keywords: ["writing", "documentation", "api", "technical", "manuals"],
    suitableFor: ["writers with technical interest", "detail-oriented", "communicators"],
  },
  {
    id: "project_manager",
    title: "Project Manager",
    category: "Management",
    entryDifficulty: "intermediate",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "6–18 months",
    keywords: ["projects", "management", "agile", "scrum", "planning", "teams"],
    suitableFor: ["organized people", "natural leaders", "problem-solvers"],
  },
  {
    id: "real_estate_agent",
    title: "Real Estate Agent",
    category: "Property",
    entryDifficulty: "beginner",
    startupCost: "low",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "very_high",
    requiresLaptop: false,
    requiresInternet: true,
    requiresPhysicalPresence: true,
    beginnerFriendly: true,
    timeToFirstIncome: "1–6 months",
    keywords: ["property", "housing", "real estate", "land", "rent", "sales"],
    suitableFor: ["salespeople", "networkers", "charismatic communicators"],
  },
  {
    id: "nurse",
    title: "Nurse",
    category: "Healthcare",
    entryDifficulty: "advanced",
    startupCost: "high",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "3–5 years",
    keywords: ["healthcare", "hospital", "patients", "medical", "caring"],
    suitableFor: ["empathetic people", "science lovers", "helpers"],
  },
  {
    id: "lawyer",
    title: "Lawyer",
    category: "Legal",
    entryDifficulty: "advanced",
    startupCost: "high",
    remoteFriendly: false,
    africaDemand: "high",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "4–7 years",
    keywords: ["law", "legal", "court", "justice", "advocacy", "rights"],
    suitableFor: ["logical arguers", "research-oriented", "justice-driven people"],
  },
  {
    id: "agricultural_entrepreneur",
    title: "Agricultural Entrepreneur",
    category: "Agriculture",
    entryDifficulty: "beginner",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: true,
    timeToFirstIncome: "3–12 months",
    keywords: ["farming", "food", "agriculture", "poultry", "crops", "fish", "agribusiness"],
    suitableFor: ["rural entrepreneurs", "nature lovers", "business-minded people without tech"],
  },
  {
    id: "translator",
    title: "Translator / Interpreter",
    category: "Language Services",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "medium",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "2–8 weeks",
    keywords: ["language", "translation", "french", "arabic", "yoruba", "hausa", "igbo"],
    suitableFor: ["bilingual or multilingual people", "detail-oriented writers", "cultural bridges"],
  },
  {
    id: "solar_specialist",
    title: "Solar Installation Specialist",
    category: "Trades",
    entryDifficulty: "intermediate",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "3–9 months",
    keywords: ["solar", "renewable energy", "electricity", "installation", "power"],
    suitableFor: ["electricians upskilling", "technical hands-on people", "green energy advocates"],
  },
  {
    id: "customer_service",
    title: "Customer Service Representative",
    category: "Operations",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "medium",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–4 weeks",
    keywords: ["customer support", "communication", "helpdesk", "crm", "service"],
    suitableFor: ["patient communicators", "problem-solvers", "empathetic people"],
  },
  {
    id: "recruitment_consultant",
    title: "Recruitment Consultant",
    category: "Human Resources",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–3 months",
    keywords: ["hiring", "recruitment", "linkedin", "talent", "headhunting", "sourcing"],
    suitableFor: ["social connectors", "salespeople", "people who like reading people"],
  },
  {
    id: "ml_engineer",
    title: "Machine Learning Engineer",
    category: "Technology",
    entryDifficulty: "advanced",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "12–24 months",
    keywords: ["ai", "machine learning", "deep learning", "models", "python", "tensorflow"],
    suitableFor: ["mathematics and programming lovers", "researchers", "existing data scientists"],
  },
  {
    id: "podcast_host",
    title: "Podcast Host",
    category: "Media",
    entryDifficulty: "beginner",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "medium",
    requiresLaptop: false,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "6–18 months",
    keywords: ["podcast", "audio", "talking", "interviews", "storytelling"],
    suitableFor: ["good speakers", "story lovers", "niche experts"],
  },
  {
    id: "blockchain_developer",
    title: "Blockchain Developer",
    category: "Technology",
    entryDifficulty: "advanced",
    startupCost: "free",
    remoteFriendly: true,
    africaDemand: "growing",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "8–18 months",
    keywords: ["blockchain", "web3", "crypto", "nft", "smart contracts", "defi"],
    suitableFor: ["experienced developers", "crypto enthusiasts", "financial tech builders"],
  },
  {
    id: "plumber",
    title: "Plumber",
    category: "Trades",
    entryDifficulty: "intermediate",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "6–18 months",
    keywords: ["plumbing", "pipes", "water", "installation", "repair", "trade"],
    suitableFor: ["practical problem-solvers", "physically capable", "trade enthusiasts"],
  },
  {
    id: "fashion_designer",
    title: "Fashion Designer",
    category: "Creative",
    entryDifficulty: "intermediate",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: true,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "3–9 months",
    keywords: ["fashion", "clothing", "tailoring", "design", "sewing", "style"],
    suitableFor: ["creative people", "fashion lovers", "visual thinkers"],
  },
  {
    id: "chef_caterer",
    title: "Chef / Caterer",
    category: "Food & Hospitality",
    entryDifficulty: "beginner",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: true,
    timeToFirstIncome: "1–4 weeks",
    keywords: ["cooking", "food", "catering", "events", "restaurant", "chef"],
    suitableFor: ["food lovers", "event people", "entrepreneurs without tech background"],
  },
  {
    id: "pharmacist",
    title: "Pharmacist",
    category: "Healthcare",
    entryDifficulty: "advanced",
    startupCost: "high",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "5–6 years",
    keywords: ["pharmacy", "medicine", "drugs", "healthcare", "chemist", "dispensing"],
    suitableFor: ["science lovers", "detail-oriented", "healthcare advocates"],
  },
  {
    id: "logistics_courier",
    title: "Logistics / Courier",
    category: "Operations",
    entryDifficulty: "beginner",
    startupCost: "low",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "medium",
    requiresLaptop: false,
    requiresInternet: true,
    requiresPhysicalPresence: true,
    beginnerFriendly: true,
    timeToFirstIncome: "1–2 weeks",
    keywords: ["delivery", "logistics", "courier", "dispatch", "transport", "ecommerce support"],
    suitableFor: ["physically active people", "entrepreneurs", "people with motorcycles or cars"],
  },
  {
    id: "makeup_artist",
    title: "Makeup Artist",
    category: "Beauty",
    entryDifficulty: "beginner",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: true,
    requiresPhysicalPresence: true,
    beginnerFriendly: true,
    timeToFirstIncome: "1–4 weeks",
    keywords: ["makeup", "beauty", "bridal", "events", "artistry", "mua"],
    suitableFor: ["creative people", "beauty lovers", "people with hand artistry"],
  },
  {
    id: "mechanic",
    title: "Auto Mechanic",
    category: "Trades",
    entryDifficulty: "intermediate",
    startupCost: "medium",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "high",
    requiresLaptop: false,
    requiresInternet: false,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "6–18 months",
    keywords: ["car", "vehicle", "repair", "mechanic", "engine", "auto"],
    suitableFor: ["hands-on technical people", "car enthusiasts", "trade learners"],
  },
  {
    id: "music_producer",
    title: "Music Producer",
    category: "Creative",
    entryDifficulty: "intermediate",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "high",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: false,
    timeToFirstIncome: "3–12 months",
    keywords: ["music", "beats", "afrobeats", "sound", "production", "daw"],
    suitableFor: ["music lovers", "creative minds", "people with an ear for sound"],
  },
  {
    id: "civil_engineer",
    title: "Civil Engineer",
    category: "Engineering",
    entryDifficulty: "advanced",
    startupCost: "high",
    remoteFriendly: false,
    africaDemand: "very_high",
    incomePotential: "very_high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "4–6 years",
    keywords: ["engineering", "construction", "buildings", "roads", "infrastructure"],
    suitableFor: ["mathematics and science lovers", "builders", "infrastructure visionaries"],
  },
  {
    id: "interior_designer",
    title: "Interior Designer",
    category: "Design",
    entryDifficulty: "intermediate",
    startupCost: "low",
    remoteFriendly: false,
    africaDemand: "growing",
    incomePotential: "high",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: true,
    beginnerFriendly: false,
    timeToFirstIncome: "3–9 months",
    keywords: ["interior design", "decor", "spaces", "homes", "offices", "aesthetics"],
    suitableFor: ["visual creatives", "spatial thinkers", "people with aesthetic taste"],
  },
  {
    id: "it_support",
    title: "IT Support Specialist",
    category: "Technology",
    entryDifficulty: "beginner",
    startupCost: "low",
    remoteFriendly: true,
    africaDemand: "very_high",
    incomePotential: "medium",
    requiresLaptop: true,
    requiresInternet: true,
    requiresPhysicalPresence: false,
    beginnerFriendly: true,
    timeToFirstIncome: "1–4 months",
    keywords: ["it support", "help desk", "computer repair", "networking", "tech support"],
    suitableFor: ["tech enthusiasts", "problem-solvers", "people good at explaining"],
  },
];
