// src/lib/basic/careerKnowledge/careerTextKnowledge.ts

export interface CareerEntry {
  title: string;
  keywords: string[];
  overview: string;
  responsibilities: string[];
  skills_required: string[];
  tools_used: string[];
  how_to_start: string[];
  monetization_paths: string[];
  salary_range_africa: string;
  where_to_learn: string[];
  common_mistakes: string[];
  next_step: string;
}

export const careerTextEntries: CareerEntry[] = [
  {
    title: "Freelancing",
    keywords: ["freelancing", "how to freelance", "start freelancing", "freelance tips", "get clients", "freelance work"],
    overview: "Freelancing means working for multiple clients on a project basis instead of a single employer. You set your own rates, hours, and choose your clients.",
    responsibilities: ["Deliver projects on time", "Communicate with clients", "Invoice and manage payments", "Market your services", "Maintain your portfolio"],
    skills_required: ["A marketable skill (writing, design, coding, etc.)", "Client communication", "Time management", "Basic business sense"],
    tools_used: ["Upwork", "Fiverr", "Toptal", "Trello", "Notion", "PayPal", "Paystack", "Wave Accounting"],
    how_to_start: ["Pick one specific service", "Build 2–3 portfolio samples", "Create profiles on Upwork and Fiverr", "Start at slightly below market rate to build reviews", "Raise rates after first 5 clients"],
    monetization_paths: ["Per project pricing", "Hourly rates", "Retainer agreements", "Monthly packages"],
    salary_range_africa: "₦50,000–₦500,000+/month depending on skill and niche. Top earners on global platforms earn $2,000–$10,000+/month.",
    where_to_learn: ["Upwork Academy", "Fiverr Learn", "YouTube", "Coursera", "freeCodeCamp (for tech skills)"],
    common_mistakes: ["Taking every client regardless of fit", "Underpricing and burning out", "No contract before starting", "Mixing personal and business money"],
    next_step: "Write a one-sentence description of the specific service you want to offer and who you want to serve.",
  },
  {
    title: "Web Developer",
    keywords: ["web developer", "web development", "frontend developer", "backend developer", "full stack", "become a web developer"],
    overview: "Web developers build websites and web applications. Frontend developers handle what users see; backend developers manage servers and databases; full-stack developers do both.",
    responsibilities: ["Write clean, maintainable code", "Build responsive user interfaces", "Connect frontends to APIs and databases", "Test and debug applications", "Collaborate with designers"],
    skills_required: ["HTML, CSS, JavaScript", "A framework (React, Vue, or Angular)", "Git and version control", "Basic command line", "Problem-solving"],
    tools_used: ["VS Code", "GitHub", "React", "Node.js", "Figma", "Postman", "Vercel", "Firebase"],
    how_to_start: ["Learn HTML and CSS first", "Add JavaScript", "Build 3 real projects", "Learn React or Vue", "Deploy on Vercel or Netlify", "Apply for junior roles or freelance"],
    monetization_paths: ["Employed developer (₦150k–₦800k+/month)", "Freelance web projects", "SaaS product revenue", "Template and theme sales"],
    salary_range_africa: "Junior: ₦80,000–₦200,000/month. Mid: ₦200,000–₦500,000/month. Senior/remote: $3,000–$8,000+/month.",
    where_to_learn: ["The Odin Project (free)", "freeCodeCamp (free)", "Scrimba", "Udemy", "roadmap.sh"],
    common_mistakes: ["Switching languages every few weeks", "Not building real projects", "Tutorial hell — watching without doing", "Ignoring Git from day one"],
    next_step: "Go to The Odin Project or freeCodeCamp and complete the first HTML/CSS module today.",
  },
  {
    title: "UI/UX Designer",
    keywords: ["ui ux designer", "ui designer", "ux designer", "user interface", "user experience", "become a designer", "product design"],
    overview: "UI/UX designers create the look, feel, and usability of digital products. UI focuses on visual design; UX focuses on how easy and satisfying a product is to use.",
    responsibilities: ["Create wireframes and mockups", "Conduct user research", "Design user flows", "Build interactive prototypes", "Collaborate with developers", "Run usability tests"],
    skills_required: ["Visual design principles", "Prototyping", "User research", "Information architecture", "Communication and empathy"],
    tools_used: ["Figma", "Adobe XD", "Sketch", "Maze", "Miro", "Notion", "Canva"],
    how_to_start: ["Learn Figma (free tier available)", "Study design principles", "Redesign existing apps as practice", "Build a case study portfolio with 3 projects", "Apply on Behance and Dribbble"],
    monetization_paths: ["Employed product designer", "Freelance UI design", "Design system creation", "UX consulting"],
    salary_range_africa: "Junior: ₦80,000–₦200,000/month. Mid-level: ₦250,000–₦600,000/month. Remote: $2,000–$6,000/month.",
    where_to_learn: ["Google UX Design Certificate (Coursera)", "Designlab", "Interaction Design Foundation", "YouTube (AJ&Smart, Figma official)"],
    common_mistakes: ["Skipping user research and just designing what looks good", "No real case studies — only pretty mockups", "Not explaining design decisions in interviews"],
    next_step: "Download Figma free, find an app you use daily, and redesign one screen from scratch.",
  },
  {
    title: "Data Analyst",
    keywords: ["data analyst", "data analysis", "become a data analyst", "data analytics", "excel analyst", "sql analyst"],
    overview: "Data analysts collect, clean, and interpret data to help organizations make better decisions. They turn raw numbers into actionable insights through visualization and reporting.",
    responsibilities: ["Collect and clean datasets", "Perform exploratory data analysis", "Build dashboards and reports", "Identify trends and patterns", "Present findings to stakeholders"],
    skills_required: ["Excel or Google Sheets", "SQL", "Python or R (optional but valuable)", "Data visualization", "Statistical thinking"],
    tools_used: ["Excel", "SQL (MySQL, PostgreSQL)", "Python (Pandas, Matplotlib)", "Power BI", "Tableau", "Google Looker Studio", "Jupyter Notebook"],
    how_to_start: ["Master Excel and SQL first", "Take a free data analysis course", "Work on a public dataset (Kaggle)", "Build a portfolio of 3 real analysis projects", "Apply for analyst or BI roles"],
    monetization_paths: ["Employed data analyst", "Freelance data projects", "Dashboard creation services", "Data consulting"],
    salary_range_africa: "Entry: ₦100,000–₦250,000/month. Mid: ₦300,000–₦600,000/month. Remote/international: $2,500–$7,000/month.",
    where_to_learn: ["Google Data Analytics Certificate (Coursera)", "Mode Analytics Tutorial", "W3Schools SQL", "Kaggle Learn", "DataCamp (paid)"],
    common_mistakes: ["Skipping SQL and going straight to Python", "No portfolio — just certificates", "Not learning to communicate findings clearly"],
    next_step: "Download a public dataset from Kaggle and analyze it using Excel. Ask one specific business question and answer it with the data.",
  },
  {
    title: "Graphic Designer",
    keywords: ["graphic designer", "graphic design", "become a graphic designer", "logo design", "visual design"],
    overview: "Graphic designers create visual content — logos, branding, social media graphics, flyers, packaging, and more — for businesses and individuals.",
    responsibilities: ["Design logos and brand identities", "Create social media graphics", "Design print and digital materials", "Work with client briefs", "Prepare files for print and web"],
    skills_required: ["Color theory and typography", "Layout and composition", "Adobe Creative Suite or Canva", "Client communication", "File preparation"],
    tools_used: ["Adobe Illustrator", "Adobe Photoshop", "Canva", "Figma", "CorelDRAW", "Affinity Designer"],
    how_to_start: ["Learn Canva for quick start or Adobe Illustrator for professional work", "Build a portfolio of 5 sample projects", "Join local business WhatsApp groups to offer services", "Create a profile on Fiverr"],
    monetization_paths: ["Logo and branding packages", "Social media management retainers", "Print design for events", "Brand identity projects"],
    salary_range_africa: "Freelance: ₦20,000–₦200,000+ per project. Employed: ₦80,000–₦300,000/month.",
    where_to_learn: ["YouTube (Satori Graphics, Will Paterson)", "Skillshare", "Adobe tutorials", "Canva Design School"],
    common_mistakes: ["Doing everything (logo, flyer, web, video) instead of specializing", "No pricing structure", "Undercharging and not raising rates"],
    next_step: "Design a logo for a fictional business today and add it to your portfolio.",
  },
  {
    title: "Content Creator",
    keywords: ["content creator", "how to become a content creator", "youtube creator", "tiktok creator", "social media creator", "content creation"],
    overview: "Content creators produce videos, articles, podcasts, or social media posts around a niche topic and build an audience they can eventually monetize.",
    responsibilities: ["Create consistent content", "Grow and engage an audience", "Manage social media platforms", "Collaborate with brands", "Analyze performance metrics"],
    skills_required: ["Video production or writing (depending on format)", "Basic editing", "Storytelling", "Understanding of platform algorithms", "Audience engagement"],
    tools_used: ["Canva", "CapCut", "DaVinci Resolve", "Notion", "Buffer", "TubeBuddy", "Anchor (podcast)"],
    how_to_start: ["Pick one platform and one niche", "Post consistently for 90 days before evaluating results", "Study what works in your niche", "Optimize titles and thumbnails", "Engage with every comment early on"],
    monetization_paths: ["Brand sponsorships", "YouTube AdSense", "Digital product sales", "Paid communities", "Affiliate marketing", "Merchandise"],
    salary_range_africa: "Varies widely. Micro-influencers (10k–50k followers): ₦30,000–₦200,000/month from brand deals. Top creators earn millions monthly.",
    where_to_learn: ["YouTube Creator Academy", "Think Media (YouTube)", "Pat Flynn (podcasting)", "Ali Abdaal (productivity content)"],
    common_mistakes: ["Starting without a niche", "Giving up before 6 months", "Chasing every platform at once", "Ignoring analytics"],
    next_step: "Choose one platform and one niche. Record your first piece of content today — it does not need to be perfect.",
  },
  {
    title: "Virtual Assistant",
    keywords: ["virtual assistant", "va", "online assistant", "remote assistant", "become a virtual assistant", "va jobs"],
    overview: "Virtual assistants provide remote administrative, technical, or creative support to businesses and entrepreneurs. It is one of the easiest remote careers to start with existing skills.",
    responsibilities: ["Email and calendar management", "Data entry and research", "Social media scheduling", "Customer support", "Travel booking", "Document creation"],
    skills_required: ["Organization and time management", "Communication", "Computer skills", "Attention to detail", "Reliability"],
    tools_used: ["Google Workspace", "Zoom", "Slack", "Trello", "Asana", "Buffer", "LastPass"],
    how_to_start: ["List all your current computer skills", "Create a service package", "Sign up on Upwork, Fiverr, or VA-specific boards", "Reach out to entrepreneurs and small business owners", "Aim for your first client within 2 weeks"],
    monetization_paths: ["Hourly rate ($5–$30/hour for beginners)", "Monthly retainers ($200–$1,500/month)", "Specialized niches (legal VA, real estate VA) command higher rates"],
    salary_range_africa: "Beginners: $3–$8/hour on global platforms. With experience and specialization: $15–$35/hour.",
    where_to_learn: ["Horkey Handbook VA course", "YouTube", "Skillshare", "90 Day VA"],
    common_mistakes: ["Not specializing in a niche", "Underpricing and overcommitting", "No contract with clients"],
    next_step: "Write a list of 10 tasks you can confidently do for a business owner right now. That is your starter service list.",
  },
  {
    title: "Social Media Manager",
    keywords: ["social media manager", "social media management", "smm", "instagram manager", "facebook manager", "social media marketing"],
    overview: "Social media managers run social media accounts for businesses — creating content, growing audiences, and driving engagement and sales.",
    responsibilities: ["Create and schedule content", "Write captions and hashtags", "Run paid ads (optional)", "Monitor analytics", "Engage with followers", "Build content calendars"],
    skills_required: ["Content creation", "Copywriting", "Analytics interpretation", "Understanding of each platform's algorithm", "Basic graphic design"],
    tools_used: ["Canva", "Buffer", "Hootsuite", "Meta Business Suite", "Later", "Google Analytics"],
    how_to_start: ["Learn 1–2 platforms deeply", "Grow your own social media as proof", "Offer free or discounted management to 1 local business", "Get a testimonial", "Scale to paid clients"],
    monetization_paths: ["Monthly management retainers (₦30,000–₦200,000/month per client)", "Content creation packages", "Ad management with performance fee"],
    salary_range_africa: "Entry: ₦50,000–₦150,000/month. Experienced: ₦200,000–₦500,000/month. Remote: $800–$3,000/month.",
    where_to_learn: ["Meta Blueprint (free)", "HubSpot Academy (free)", "Buffer Blog", "YouTube"],
    common_mistakes: ["Managing clients' accounts without a documented strategy", "Posting without analyzing performance", "Not having a clear content calendar"],
    next_step: "Pick one business you like, create a free 7-day content calendar for their Instagram, and send it to them as a proposal.",
  },
  {
    title: "Electrician",
    keywords: ["electrician", "electrical technician", "how to become an electrician", "electrical work", "electrical engineering technician"],
    overview: "Electricians install, maintain, and repair electrical systems in homes, businesses, and industrial facilities. It is a high-demand trade in Africa.",
    responsibilities: ["Install wiring and electrical panels", "Repair faulty circuits", "Install solar and inverter systems", "Read electrical blueprints", "Ensure electrical safety compliance"],
    skills_required: ["Electrical theory", "Wiring and circuit installation", "Safety protocols", "Reading technical diagrams", "Problem-solving"],
    tools_used: ["Multimeter", "Wire stripper", "Conduit bender", "Circuit tester", "Drill and hand tools"],
    how_to_start: ["Complete a vocational/technical training program (6–24 months)", "Apprentice under a licensed electrician", "Get certified by a national electrical licensing body", "Start with residential work", "Expand to commercial and solar installation"],
    monetization_paths: ["Service calls", "Installation contracts", "Solar panel installation", "Maintenance contracts with businesses", "Own an electrical contracting company"],
    salary_range_africa: "Junior: ₦60,000–₦150,000/month. Experienced: ₦200,000–₦500,000/month. Solar specialists and contractors can earn more.",
    where_to_learn: ["Technical colleges", "NABTEB or vocational centers (Nigeria)", "ARTC (Ghana)", "Apprenticeship programs"],
    common_mistakes: ["Working without safety training", "Not getting certified", "Undercharging for specialized work like solar"],
    next_step: "Find a certified electrician in your area and arrange a 2-week observation/apprenticeship this week.",
  },
  {
    title: "Video Editor",
    keywords: ["video editor", "video editing", "how to become a video editor", "content editing", "youtube editor", "film editor"],
    overview: "Video editors cut and assemble raw footage into finished videos for YouTube, films, social media, and businesses. Demand is growing rapidly with video content creation.",
    responsibilities: ["Cut and arrange footage", "Add music, sound effects, and color grading", "Create graphics and text overlays", "Export for different platforms", "Work to creative briefs"],
    skills_required: ["Video editing software", "Storytelling and pacing", "Color grading basics", "Audio cleanup", "Attention to detail"],
    tools_used: ["DaVinci Resolve (free)", "Adobe Premiere Pro", "CapCut (mobile)", "Final Cut Pro (Mac)", "After Effects (motion graphics)"],
    how_to_start: ["Learn DaVinci Resolve (free and professional)", "Edit 10 videos for free to build portfolio", "Approach YouTube creators and offer to edit 1 video for free", "Convert them to paying clients"],
    monetization_paths: ["Per video pricing (₦5,000–₦100,000+ per video)", "Monthly retainer with content creators", "Corporate video production", "Wedding and event videography"],
    salary_range_africa: "Freelance: ₦30,000–₦300,000+/month. Remote editing for international creators: $500–$3,000/month.",
    where_to_learn: ["DaVinci Resolve free tutorials on YouTube", "Premiere Gal (YouTube)", "Corridor Crew (YouTube)", "Skillshare"],
    common_mistakes: ["Editing without understanding storytelling", "Overusing effects and transitions", "No clear pricing structure"],
    next_step: "Download DaVinci Resolve free today and edit a 3-minute video from publicly available footage.",
  },
  {
    title: "Copywriter",
    keywords: ["copywriter", "copywriting", "how to become a copywriter", "writing for money", "sales copywriting", "email copywriting"],
    overview: "Copywriters write persuasive text that sells — website copy, email campaigns, ads, sales pages, product descriptions, and more.",
    responsibilities: ["Write sales pages and landing pages", "Email sequences and newsletters", "Ad copy for social media and Google", "Product descriptions", "Brand voice development"],
    skills_required: ["Persuasive writing", "Understanding of buyer psychology", "Research ability", "Grammar and clarity", "Headline writing"],
    tools_used: ["Google Docs", "Hemingway Editor", "Jasper or Copy.ai (AI assistance)", "Mailchimp", "ConvertKit"],
    how_to_start: ["Study foundational copywriting books (Ogilvy, Halbert, Sugarman)", "Write 10 sample pieces in different formats", "Get your first client through Upwork or local business outreach", "Specialize in a niche (email, ads, B2B)"],
    monetization_paths: ["Project-based fees", "Retainer for ongoing email campaigns", "Revenue share deals", "Agency work"],
    salary_range_africa: "Beginner: ₦50,000–₦150,000/month. Experienced: ₦300,000–₦800,000/month. Top email copywriters earn $5,000–$20,000+/month remotely.",
    where_to_learn: ["CopyHackers", "AWAI", "The Copywriter Club", "Books: Ogilvy on Advertising, The Boron Letters"],
    common_mistakes: ["Writing without research", "Not understanding what the reader wants", "No specialization — writing everything for everyone"],
    next_step: "Rewrite the homepage of a local business in your area as a portfolio sample.",
  },
  {
    title: "Software Developer",
    keywords: ["software developer", "software engineer", "programmer", "how to become a software developer", "coding career"],
    overview: "Software developers design, build, and maintain software systems — apps, tools, platforms, and infrastructure. It is one of the highest-paying and most in-demand careers globally.",
    responsibilities: ["Write and review code", "Design system architecture", "Debug and test software", "Collaborate with product and design teams", "Document technical decisions"],
    skills_required: ["Programming languages (Python, JavaScript, Java, etc.)", "Data structures and algorithms", "Version control (Git)", "System design", "Problem-solving"],
    tools_used: ["VS Code", "GitHub", "Docker", "AWS or GCP", "Jira", "Slack", "Postman"],
    how_to_start: ["Pick one language (Python or JavaScript recommended for beginners)", "Learn fundamentals for 3–6 months", "Build 3 real projects", "Practice data structures and algorithms (LeetCode)", "Apply for internships or junior roles"],
    monetization_paths: ["Employed software engineer", "Freelance development", "SaaS product", "Open source contributions → job offers", "Remote work on international teams"],
    salary_range_africa: "Junior: ₦150,000–₦400,000/month locally. Remote: $3,000–$10,000+/month for senior engineers.",
    where_to_learn: ["The Odin Project (free)", "freeCodeCamp (free)", "CS50 Harvard (free)", "Udemy", "roadmap.sh"],
    common_mistakes: ["Switching languages constantly", "Skipping the fundamentals", "Not building real projects", "Avoiding algorithms"],
    next_step: "Go to CS50x on edX or The Odin Project and complete the first week of material this week.",
  },
  {
    title: "Digital Marketer",
    keywords: ["digital marketer", "digital marketing", "online marketing", "performance marketing", "digital marketing career"],
    overview: "Digital marketers promote businesses online using SEO, paid ads, email, social media, and content to attract and convert customers.",
    responsibilities: ["Plan and run digital campaigns", "Manage SEO and content strategy", "Run Google and Meta ads", "Email marketing", "Track and analyze campaign performance"],
    skills_required: ["Understanding of marketing funnels", "Analytics and data interpretation", "Copywriting", "SEO basics", "Paid advertising"],
    tools_used: ["Google Analytics", "Meta Ads Manager", "Google Ads", "Mailchimp", "SEMrush", "Ahrefs", "HubSpot"],
    how_to_start: ["Get a free Google Digital Garage certificate", "Run a ₦5,000 test ad for a local business", "Learn Google Analytics", "Build a case study from your first campaign", "Apply for agency roles or freelance"],
    monetization_paths: ["Employed marketer", "Freelance campaign management", "Performance-based retainers", "Affiliate marketing", "Marketing agency"],
    salary_range_africa: "Entry: ₦80,000–₦200,000/month. Mid: ₦250,000–₦500,000/month. Performance marketers can earn significantly more.",
    where_to_learn: ["Google Digital Garage (free)", "HubSpot Academy (free)", "Meta Blueprint (free)", "Coursera Digital Marketing Certificate"],
    common_mistakes: ["Running ads without understanding the target audience", "No tracking or analytics setup", "Ignoring organic channels"],
    next_step: "Sign up for Google Digital Garage today and complete Module 1 this week.",
  },
  {
    title: "Data Scientist",
    keywords: ["data scientist", "data science", "machine learning", "ai career", "become a data scientist"],
    overview: "Data scientists build models and systems that extract insights, make predictions, and automate decisions from large datasets using statistics and machine learning.",
    responsibilities: ["Build and deploy ML models", "Clean and prepare large datasets", "Conduct statistical analysis", "Communicate findings to business stakeholders", "Collaborate with engineering teams"],
    skills_required: ["Python and SQL", "Statistics and probability", "Machine learning (scikit-learn, TensorFlow, PyTorch)", "Data visualization", "Communication"],
    tools_used: ["Python", "Jupyter Notebook", "Pandas", "Scikit-learn", "TensorFlow", "Tableau", "BigQuery", "Spark"],
    how_to_start: ["Master Python and SQL first", "Take a structured data science course", "Work on 3 Kaggle competitions", "Build a portfolio with GitHub projects", "Apply for data analyst roles first as a stepping stone"],
    monetization_paths: ["Employed data scientist", "Freelance ML projects", "Kaggle competitions (cash prizes)", "AI consulting", "SaaS product using ML"],
    salary_range_africa: "Mid-level locally: ₦300,000–₦800,000/month. Remote: $5,000–$15,000+/month for senior roles.",
    where_to_learn: ["fast.ai (free)", "Kaggle Learn (free)", "Coursera Machine Learning (Andrew Ng)", "DataCamp", "DeepLearning.ai"],
    common_mistakes: ["Jumping to deep learning before mastering the basics", "No real portfolio — only certificates", "Not learning how to communicate results"],
    next_step: "Complete the Kaggle Python course this week and start your first notebook on a public dataset.",
  },
  {
    title: "Cybersecurity Analyst",
    keywords: ["cybersecurity", "cyber security analyst", "ethical hacker", "penetration tester", "information security", "cybersecurity career"],
    overview: "Cybersecurity analysts protect organizations from digital threats by monitoring systems, identifying vulnerabilities, and responding to incidents.",
    responsibilities: ["Monitor systems for threats", "Conduct vulnerability assessments", "Respond to security incidents", "Implement security policies", "Penetration testing"],
    skills_required: ["Networking fundamentals", "Linux basics", "Security tools (Wireshark, Nmap, Metasploit)", "Cryptography basics", "Analytical thinking"],
    tools_used: ["Kali Linux", "Wireshark", "Burp Suite", "Nmap", "Metasploit", "Splunk", "IBM QRadar"],
    how_to_start: ["Get CompTIA Security+ certification", "Practice on TryHackMe or Hack The Box", "Learn Linux", "Build a home lab", "Pursue CEH or OSCP for advanced roles"],
    monetization_paths: ["Employed security analyst", "Freelance penetration testing", "Bug bounty programs", "Security consulting", "Training and certification prep"],
    salary_range_africa: "Entry: ₦150,000–₦350,000/month. Senior: ₦500,000–₦1,000,000/month. Remote: $4,000–$12,000+/month.",
    where_to_learn: ["TryHackMe (free tier)", "Cybrary (free tier)", "CompTIA Security+ study material", "Professor Messer (YouTube)"],
    common_mistakes: ["Jumping to hacking before learning networking basics", "No certifications", "Not building a portfolio of CTF challenges"],
    next_step: "Create a free TryHackMe account and complete the pre-security learning path this week.",
  },
  {
    title: "Cloud Engineer",
    keywords: ["cloud engineer", "cloud computing", "aws", "azure", "gcp", "devops", "cloud career"],
    overview: "Cloud engineers design, build, and manage cloud infrastructure for organizations on platforms like AWS, Azure, and Google Cloud.",
    responsibilities: ["Design cloud architecture", "Manage servers and databases", "Automate infrastructure (IaC)", "Monitor performance and costs", "Implement security best practices"],
    skills_required: ["Linux and networking", "One major cloud platform (AWS, Azure, or GCP)", "Terraform or Ansible", "Docker and Kubernetes", "Scripting (Python or Bash)"],
    tools_used: ["AWS", "Azure", "GCP", "Terraform", "Docker", "Kubernetes", "GitHub Actions", "Prometheus"],
    how_to_start: ["Get AWS Cloud Practitioner certification first", "Set up a free AWS account and build projects", "Progress to AWS Solutions Architect Associate", "Learn Docker and Terraform", "Build a portfolio of cloud projects"],
    monetization_paths: ["Employed cloud engineer", "Cloud consulting", "Freelance DevOps projects", "Remote work for international companies"],
    salary_range_africa: "Entry: ₦200,000–₦400,000/month. Senior: ₦600,000–₦1,200,000/month. Remote: $5,000–$15,000+/month.",
    where_to_learn: ["AWS Training (free tier)", "Linux Foundation courses", "A Cloud Guru", "freeCodeCamp (DevOps)", "TechWorld with Nana (YouTube)"],
    common_mistakes: ["Going too broad — trying to learn all three clouds at once", "No hands-on projects, only theory", "Skipping Linux fundamentals"],
    next_step: "Create a free AWS account and deploy a static website using S3 this week.",
  },
  {
    title: "Product Manager",
    keywords: ["product manager", "product management", "pm career", "how to become a product manager", "tech product manager"],
    overview: "Product managers define what gets built, why, and when. They bridge business, design, and engineering to ensure products solve real user problems and achieve business goals.",
    responsibilities: ["Define product vision and roadmap", "Gather and prioritize user requirements", "Work with engineering, design, and marketing", "Analyze metrics and user feedback", "Write PRDs and user stories"],
    skills_required: ["Strategic thinking", "Data analysis", "User research", "Communication and stakeholder management", "Basic technical understanding"],
    tools_used: ["Jira", "Notion", "Figma", "Amplitude", "Mixpanel", "Miro", "Confluence", "Slack"],
    how_to_start: ["Read Inspired by Marty Cagan", "Get a Product Management certificate (Coursera or reforge)", "Practice with side project or open source", "Transition from existing tech, design, or business role", "Apply for APM programs"],
    monetization_paths: ["Employed PM (highest salaries in tech)", "Freelance product consulting", "Startup founder (using PM skills)"],
    salary_range_africa: "Mid-level: ₦400,000–₦900,000/month. Senior/Director: ₦1,000,000+/month. Remote: $6,000–$20,000+/month.",
    where_to_learn: ["Inspired (Marty Cagan)", "Reforge", "Product School", "Coursera PM Certificates", "Lenny's Newsletter"],
    common_mistakes: ["Thinking PM is about managing people not products", "No metrics or data in their portfolio", "Weak communication skills"],
    next_step: "Read the first 3 chapters of Inspired by Marty Cagan and write one user story for a product you use daily.",
  },
  {
    title: "Mobile App Developer",
    keywords: ["mobile app developer", "android developer", "ios developer", "react native", "flutter developer", "app development"],
    overview: "Mobile app developers build applications for Android and iOS devices. Cross-platform frameworks like Flutter and React Native allow one codebase for both platforms.",
    responsibilities: ["Build mobile app features", "Integrate APIs and backend services", "Test on real devices and emulators", "Publish apps to Play Store and App Store", "Fix bugs and improve performance"],
    skills_required: ["JavaScript (React Native) or Dart (Flutter)", "Mobile UI patterns", "REST API integration", "App store publishing", "Testing and debugging"],
    tools_used: ["Flutter", "React Native", "Android Studio", "Xcode", "Firebase", "Expo", "VS Code"],
    how_to_start: ["Choose Flutter (Dart) or React Native (JavaScript)", "Build 3 sample apps", "Publish a free app to the Play Store", "Grow the app or use it as a portfolio piece", "Apply for mobile roles or freelance"],
    monetization_paths: ["App monetization (ads, premium, subscriptions)", "Employed mobile developer", "Freelance app builds", "SaaS mobile apps"],
    salary_range_africa: "Entry: ₦150,000–₦350,000/month. Senior: ₦500,000–₦900,000/month. Remote: $4,000–$12,000+/month.",
    where_to_learn: ["Flutter.dev docs (free)", "The Net Ninja (YouTube)", "Academind (Udemy)", "freeCodeCamp YouTube"],
    common_mistakes: ["Building complex apps before mastering the basics", "Not testing on real devices", "Ignoring UX design principles"],
    next_step: "Install Flutter or Expo today and build a simple to-do list app by the end of the week.",
  },
  {
    title: "SEO Specialist",
    keywords: ["seo specialist", "search engine optimization", "seo career", "how to do seo", "seo expert"],
    overview: "SEO specialists optimize websites to rank higher in search engine results, driving organic traffic without paying for ads.",
    responsibilities: ["Conduct keyword research", "Optimize on-page content", "Build backlinks", "Technical SEO audits", "Track rankings and organic traffic"],
    skills_required: ["Keyword research", "On-page optimization", "Link building", "Google Search Console", "Basic HTML knowledge"],
    tools_used: ["Ahrefs", "SEMrush", "Google Search Console", "Google Analytics", "Screaming Frog", "Surfer SEO"],
    how_to_start: ["Learn SEO fundamentals through free courses", "Start your own blog and apply techniques", "Get your first client through local business outreach", "Build case studies from ranking results"],
    monetization_paths: ["Monthly SEO retainers", "Agency employment", "Affiliate SEO sites", "Consulting"],
    salary_range_africa: "Entry: ₦80,000–₦200,000/month. Experienced: ₦300,000–₦600,000/month. Remote: $2,000–$5,000+/month.",
    where_to_learn: ["Ahrefs Academy (free)", "Moz Beginner's Guide to SEO (free)", "Google Search Central (free)", "Backlinko"],
    common_mistakes: ["Focusing only on keywords and ignoring content quality", "Buying cheap backlinks", "Not tracking results with data"],
    next_step: "Go to Google Search Console and add your personal blog or a local business website. Review what keywords it already ranks for.",
  },
  {
    title: "E-commerce Entrepreneur",
    keywords: ["ecommerce", "online store", "start an online business", "sell online", "dropshipping", "shopify store"],
    overview: "E-commerce entrepreneurs sell products online — either their own or through dropshipping — using platforms like Shopify, Jumia, or Instagram.",
    responsibilities: ["Source or create products", "Set up an online store", "Market products through social media and ads", "Handle orders and customer service", "Analyze sales data"],
    skills_required: ["Basic business understanding", "Digital marketing", "Customer service", "Product photography (for physical products)", "Basic financial management"],
    tools_used: ["Shopify", "WooCommerce", "Paystack", "Flutterwave", "Jumia", "Canva", "Meta Ads"],
    how_to_start: ["Pick a product niche with demand in your market", "Source products or choose dropshipping", "Set up a Paystack store or Shopify", "Market through Instagram and Facebook", "Reinvest profits to scale"],
    monetization_paths: ["Direct product sales", "Dropshipping margins", "Private label products", "Digital products (no inventory)"],
    salary_range_africa: "Highly variable. Small stores: ₦50,000–₦300,000/month profit. Successful stores can generate millions monthly.",
    where_to_learn: ["Shopify Academy (free)", "YouTube (Verum Ecom, Biaheza)", "Paystack Merchant Blog"],
    common_mistakes: ["No market validation before investing", "Ignoring customer service", "Poor product photography"],
    next_step: "Identify 3 products with demand in your local market and research where to source them this week.",
  },
  {
    title: "Accountant",
    keywords: ["accountant", "accounting career", "chartered accountant", "acca", "ican", "bookkeeper", "financial accountant"],
    overview: "Accountants manage financial records, prepare reports, ensure tax compliance, and advise organizations on financial decisions.",
    responsibilities: ["Maintain financial records", "Prepare financial statements", "Tax filing and compliance", "Audit support", "Budgeting and forecasting"],
    skills_required: ["Accounting principles", "Financial reporting standards (IFRS/GAAP)", "Tax laws", "Excel and accounting software", "Attention to detail"],
    tools_used: ["QuickBooks", "Sage", "Microsoft Excel", "Xero", "Wave Accounting (free)", "Zoho Books"],
    how_to_start: ["Pursue ICAN (Nigeria), ACCA, or ICAG (Ghana) certification", "Get entry-level bookkeeping experience", "Master Excel and QuickBooks", "Build experience in a firm", "Later specialize in tax, audit, or advisory"],
    monetization_paths: ["Employed in company or firm", "Freelance bookkeeping", "Tax advisory practice", "CFO services for SMEs"],
    salary_range_africa: "Entry: ₦80,000–₦200,000/month. Chartered accountant: ₦300,000–₦800,000/month. CFO level: ₦1,000,000+/month.",
    where_to_learn: ["ICAN/ACCA study materials", "Coursera Financial Accounting", "AccountingCoach (free)", "YouTube"],
    common_mistakes: ["Not pursuing professional certification", "Weak Excel skills", "No experience with accounting software"],
    next_step: "Download Wave Accounting free today and practice creating a simple profit and loss statement.",
  },
  {
    title: "Human Resources Manager",
    keywords: ["human resources", "hr manager", "hr career", "people operations", "hr professional", "talent management"],
    overview: "HR managers recruit, develop, and retain talent while ensuring compliance with labor laws and building a productive workplace culture.",
    responsibilities: ["Recruit and onboard employees", "Manage employee relations", "Implement HR policies", "Handle performance management", "Ensure legal compliance"],
    skills_required: ["Communication and empathy", "Labor law knowledge", "Conflict resolution", "Organizational skills", "Data management"],
    tools_used: ["BambooHR", "Workday", "Greenhouse", "Slack", "Google Workspace", "ATS platforms"],
    how_to_start: ["Get a degree or diploma in HR, business, or psychology", "Get CIPM (Nigeria), CIPD, or SHRM certification", "Start with an administrative HR role", "Build people skills alongside technical HR knowledge"],
    monetization_paths: ["Employed HR in companies", "HR consulting for SMEs", "Training and L&D facilitation"],
    salary_range_africa: "Entry: ₦80,000–₦200,000/month. HR Manager: ₦300,000–₦700,000/month. HR Director: ₦800,000–₦2,000,000/month.",
    where_to_learn: ["CIPM Nigeria", "SHRM eLearning", "Coursera HR courses", "LinkedIn Learning"],
    common_mistakes: ["Not keeping up with labor law changes", "Treating HR as purely administrative", "Poor documentation practices"],
    next_step: "Study the Nigerian Labor Act or your country's equivalent employment law this week.",
  },
  {
    title: "Teacher / Tutor",
    keywords: ["teacher", "tutor", "online tutor", "teaching career", "become a teacher", "private tutor"],
    overview: "Teachers and tutors educate students in academic subjects or skills. Online tutoring has expanded earning potential significantly across Africa.",
    responsibilities: ["Teach and explain concepts clearly", "Create lesson plans and materials", "Assess student progress", "Give feedback and support", "Manage classroom or online sessions"],
    skills_required: ["Subject matter expertise", "Communication and patience", "Lesson planning", "Assessment design", "Adaptability"],
    tools_used: ["Zoom", "Google Meet", "Notion", "Canva", "Kahoot", "Google Classroom", "Paystack (for payments)"],
    how_to_start: ["Start tutoring subjects you are already strong in", "Offer sessions through word of mouth first", "Create a WhatsApp group for students", "Set up a Paystack payment link", "Scale to Preply, Chegg, or Tutor.com for international students"],
    monetization_paths: ["Private tutoring (₦5,000–₦50,000/hour)", "Group classes", "Online course creation", "School employment"],
    salary_range_africa: "Private tutoring: ₦50,000–₦400,000/month depending on niche and client type. International online tutoring: $15–$50/hour.",
    where_to_learn: ["Coursera Teaching courses", "YouTube Education channel strategies", "Preply training materials"],
    common_mistakes: ["Not having structured lesson plans", "Undercharging for specialized subjects", "No system for collecting payments"],
    next_step: "Define the one subject and level you will tutor first. Create a WhatsApp flyer and share it with 20 people today.",
  },
  {
    title: "Photographer",
    keywords: ["photographer", "photography career", "how to become a photographer", "portrait photographer", "wedding photographer", "product photography"],
    overview: "Photographers capture images for events, portraits, brands, products, editorial, and commercial uses. Photography is a viable and scalable career in Africa.",
    responsibilities: ["Capture photos at events or shoots", "Edit and retouch images", "Deliver files to clients", "Market services", "Manage client relationships"],
    skills_required: ["Camera operation and settings", "Lighting (natural and studio)", "Photo editing (Lightroom, Photoshop)", "Composition", "Client communication"],
    tools_used: ["DSLR or mirrorless camera", "Adobe Lightroom", "Adobe Photoshop", "Canva", "Google Drive"],
    how_to_start: ["Practice with whatever camera you have (including smartphone)", "Shoot 50 photos per week", "Build an Instagram portfolio", "Offer free shoots to friends for portfolio", "Transition to paid gigs"],
    monetization_paths: ["Wedding photography", "Event photography", "Brand and product photography", "Portrait sessions", "Stock photography (Shutterstock, Getty)"],
    salary_range_africa: "Events: ₦50,000–₦500,000+ per gig. Brand photography: ₦100,000–₦500,000 per project. Stock photos: passive income.",
    where_to_learn: ["YouTube (Peter McKinnon, Sean Tucker)", "Lightroom tutorials", "Skillshare", "Photography blogs"],
    common_mistakes: ["Not editing consistently", "Undercharging for weddings and events", "No contract with clients"],
    next_step: "Take 20 portrait photos of a willing friend or family member today and edit 5 of them.",
  },
  {
    title: "Financial Advisor",
    keywords: ["financial advisor", "financial planner", "investment advisor", "wealth manager", "personal finance career"],
    overview: "Financial advisors help individuals and businesses plan, invest, and manage their money to achieve financial goals.",
    responsibilities: ["Assess client financial situations", "Create investment and savings plans", "Advise on insurance, tax, and estate planning", "Monitor and adjust portfolios", "Educate clients on financial products"],
    skills_required: ["Finance and investment knowledge", "Communication and trust building", "Analytical thinking", "Sales ability", "Understanding of regulations"],
    tools_used: ["Financial planning software", "Excel", "Bloomberg Terminal (for investment firms)", "CRM tools"],
    how_to_start: ["Get a finance degree or relevant certification (CFA, CFP)", "Start with an entry role at a bank or investment firm", "Build a client base through networking", "Get licensed per your country's regulatory requirements"],
    monetization_paths: ["Commission-based sales", "Fee-only planning services", "Assets under management (AUM) fees", "Corporate financial advisory"],
    salary_range_africa: "Entry: ₦100,000–₦300,000/month. Senior advisors: ₦500,000–₦2,000,000+/month including commissions.",
    where_to_learn: ["CFA Institute resources", "Coursera Personal Finance courses", "Investopedia Academy"],
    common_mistakes: ["Prioritizing commissions over client interests", "Insufficient financial product knowledge", "Weak sales and communication skills"],
    next_step: "Study the basics of compound interest and investment vehicles common in your market this week.",
  },
  {
    title: "Backend Developer",
    keywords: ["backend developer", "backend development", "node.js developer", "python backend", "server side developer", "api developer"],
    overview: "Backend developers build the server-side logic, databases, and APIs that power web and mobile applications. Users never see backend code — but everything depends on it.",
    responsibilities: ["Build and maintain APIs", "Design database schemas", "Write server-side logic", "Handle authentication and security", "Optimize performance and scalability"],
    skills_required: ["Server-side language (Node.js, Python, PHP, Java, Go)", "Databases (SQL and NoSQL)", "REST APIs and GraphQL", "Authentication (JWT, OAuth)", "Git"],
    tools_used: ["Node.js", "Python/Django", "PostgreSQL", "MongoDB", "Redis", "Docker", "AWS", "Postman"],
    how_to_start: ["Learn Node.js or Python first", "Understand databases (start with PostgreSQL)", "Build a REST API from scratch", "Add authentication", "Deploy to a cloud provider"],
    monetization_paths: ["Employed backend engineer", "Freelance API development", "SaaS products", "Remote work"],
    salary_range_africa: "Junior: ₦120,000–₦300,000/month. Senior: ₦500,000–₦1,000,000/month. Remote: $4,000–$12,000+/month.",
    where_to_learn: ["The Odin Project", "freeCodeCamp (APIs and Microservices)", "Traversy Media (YouTube)", "Udemy Node.js course"],
    common_mistakes: ["Ignoring security fundamentals", "No database optimization knowledge", "Building without version control"],
    next_step: "Build a simple REST API with 3 endpoints using Node.js or Python/Flask this week.",
  },
  {
    title: "Animator",
    keywords: ["animator", "animation career", "2d animation", "3d animation", "motion graphics", "how to become an animator"],
    overview: "Animators create moving images for films, games, advertisements, social media, and educational content using 2D or 3D tools.",
    responsibilities: ["Create character rigs and animations", "Produce motion graphics", "Collaborate with directors and designers", "Meet creative briefs and deadlines", "Review and refine animations"],
    skills_required: ["Animation principles (12 principles)", "Software proficiency", "Storytelling", "Timing and pacing", "Attention to detail"],
    tools_used: ["Adobe Animate", "Blender (free)", "After Effects", "Maya", "Toon Boom Harmony"],
    how_to_start: ["Learn Blender (free and industry-standard)", "Study the 12 principles of animation", "Create a 30-second animation portfolio piece", "Post on Behance and ArtStation", "Pursue freelance or studio work"],
    monetization_paths: ["Film and TV animation", "Commercial and ad animation", "Game animation", "Explainer video production", "NFT art"],
    salary_range_africa: "Freelance: ₦50,000–₦500,000+ per project. Studio employment: ₦150,000–₦500,000/month. Remote: $2,000–$8,000/month.",
    where_to_learn: ["Blender Guru (YouTube, free)", "CG Cookie", "Animation Mentor", "Bloop Animation"],
    common_mistakes: ["Skipping the animation fundamentals", "No showreel/portfolio", "Only creating art — not storytelling"],
    next_step: "Download Blender free and complete the first donut tutorial by Blender Guru this week.",
  },
  {
    title: "Podcast Host",
    keywords: ["podcast host", "podcasting", "start a podcast", "how to podcast", "podcast career"],
    overview: "Podcast hosts create audio (and sometimes video) content around a specific topic, building an audience and monetizing through ads, sponsorships, and listener support.",
    responsibilities: ["Research and plan episodes", "Record and edit audio", "Publish and distribute episodes", "Grow and engage audience", "Pitch to sponsors"],
    skills_required: ["Clear speaking voice", "Interviewing skills", "Basic audio editing", "Consistency", "Marketing"],
    tools_used: ["Audacity (free)", "Adobe Audition", "Anchor/Spotify for Podcasters (free)", "Buzzsprout", "Canva (for artwork)"],
    how_to_start: ["Choose a specific niche", "Record 5 pilot episodes before launching", "Distribute on Spotify, Apple Podcasts, Google Podcasts", "Grow through social media clips", "Monetize after 1,000 downloads/episode average"],
    monetization_paths: ["Sponsorships", "Listener support (Patreon)", "Premium episodes", "Live events", "Consulting from authority built"],
    salary_range_africa: "Small podcasts: ₦0–₦50,000/month. Established shows: ₦200,000–₦2,000,000+/month from sponsorships.",
    where_to_learn: ["Spotify for Podcasters Academy", "Pat Flynn Smart Passive Income", "How to Start a Podcast (Riverside.fm blog)"],
    common_mistakes: ["Not choosing a specific enough niche", "Poor audio quality from the start", "Giving up before episode 50"],
    next_step: "Record a 10-minute test episode on your phone today and listen back critically.",
  },
  {
    title: "Blockchain Developer",
    keywords: ["blockchain developer", "web3 developer", "smart contracts", "solidity developer", "crypto developer", "nft developer"],
    overview: "Blockchain developers build decentralized applications, smart contracts, and blockchain infrastructure for DeFi, NFTs, supply chain, and more.",
    responsibilities: ["Write and audit smart contracts", "Build dApps (decentralized apps)", "Integrate blockchain with existing systems", "Work with Web3 libraries", "Security auditing"],
    skills_required: ["Solidity (Ethereum)", "JavaScript or Rust", "Web3.js or Ethers.js", "Understanding of blockchain concepts", "Security awareness"],
    tools_used: ["Hardhat", "Truffle", "Metamask", "Remix IDE", "IPFS", "OpenZeppelin", "Alchemy"],
    how_to_start: ["Learn Solidity fundamentals", "Build on Ethereum testnet", "Complete CryptoZombies tutorial", "Deploy your first token or NFT contract", "Build a portfolio of 3 smart contract projects"],
    monetization_paths: ["Employed Web3 developer", "Freelance smart contract development", "Building DeFi protocols", "Auditing (very lucrative)", "Bug bounties"],
    salary_range_africa: "Remote roles: $5,000–$20,000+/month. One of the highest-paid developer specializations globally.",
    where_to_learn: ["CryptoZombies (free)", "Buildspace (free)", "Alchemy University (free)", "Patrick Collins (YouTube, free)"],
    common_mistakes: ["Not understanding the underlying blockchain concepts", "Skipping security best practices", "Not auditing before deployment"],
    next_step: "Complete the CryptoZombies Chapter 1 tutorial at cryptozombies.io today.",
  },
  {
    title: "Technical Writer",
    keywords: ["technical writer", "technical writing", "documentation writer", "api documentation", "content writing technical"],
    overview: "Technical writers create documentation, user manuals, API docs, and educational content that explains complex technical topics clearly.",
    responsibilities: ["Write user guides and manuals", "Create API documentation", "Simplify complex technical processes", "Work with developers and product teams", "Maintain and update documentation"],
    skills_required: ["Clear writing", "Ability to understand technical concepts", "Research skills", "Markdown and documentation tools", "Attention to detail"],
    tools_used: ["Notion", "Confluence", "Gitbook", "Docusaurus", "Postman (for API docs)", "Grammarly", "VS Code"],
    how_to_start: ["Build writing samples on Medium or a personal blog", "Contribute to open source documentation", "Apply to developer-focused companies", "Specialize in a niche (API docs, SaaS, medical)"],
    monetization_paths: ["Employed technical writer", "Freelance documentation projects", "API documentation retainers"],
    salary_range_africa: "Entry: ₦80,000–₦200,000/month. Senior: ₦300,000–₦700,000/month. Remote: $3,000–$8,000+/month.",
    where_to_learn: ["Google Technical Writing Course (free)", "The Good Docs Project (free)", "Write the Docs community"],
    common_mistakes: ["Writing for experts instead of the target user", "Not updating documentation when products change", "No code examples in API docs"],
    next_step: "Document an API or tool you use daily as if writing for a complete beginner. Post it on Medium.",
  },
  {
    title: "Project Manager",
    keywords: ["project manager", "project management", "pmp", "agile project manager", "scrum master", "pm career"],
    overview: "Project managers plan, execute, and deliver projects on time, within budget, and to scope — across industries from construction to technology.",
    responsibilities: ["Define project scope and goals", "Create project plans and timelines", "Manage team and stakeholders", "Track progress and remove blockers", "Deliver projects and close out"],
    skills_required: ["Planning and organization", "Communication", "Risk management", "Leadership", "Budget management"],
    tools_used: ["Jira", "Asana", "Trello", "MS Project", "Notion", "Slack", "Smartsheet"],
    how_to_start: ["Get PMP or CAPM certification (or Prince2 in Commonwealth countries)", "Start with a coordinator role", "Apply Agile or Scrum in current work", "Build a portfolio of delivered projects", "Join PMI chapter for networking"],
    monetization_paths: ["Employed PM", "Freelance project management", "Consulting", "Agile coaching"],
    salary_range_africa: "Entry: ₦150,000–₦350,000/month. Senior PM: ₦500,000–₦1,200,000/month. Remote: $4,000–$10,000+/month.",
    where_to_learn: ["PMI.org", "Coursera Google Project Management Certificate (free audit)", "Scrum.org", "Agile Alliance"],
    common_mistakes: ["No formal methodology (Agile or Waterfall)", "Poor stakeholder communication", "Ignoring risk management"],
    next_step: "Create a project plan for one personal goal using Trello or Notion this week.",
  },
  {
    title: "Real Estate Agent",
    keywords: ["real estate agent", "estate agent", "property agent", "realtor", "real estate career", "property sales"],
    overview: "Real estate agents help buyers, sellers, landlords, and tenants find and transact property. High commissions make it lucrative in Africa's growing property market.",
    responsibilities: ["List and market properties", "Match clients with properties", "Negotiate deals", "Facilitate legal and financial processes", "Build and maintain client relationships"],
    skills_required: ["Sales and negotiation", "Local market knowledge", "Communication", "Basic legal understanding of property transactions", "Networking"],
    tools_used: ["Property listing platforms (PropertyPro, Jumia House)", "WhatsApp", "Google Maps", "Instagram", "Excel"],
    how_to_start: ["Shadow an established agent for 3 months", "Get licensed per your country (ESVAN in Nigeria, etc.)", "List your first property", "Build a referral network", "Specialize in residential, commercial, or land"],
    monetization_paths: ["Commission per deal (typically 5–10% of deal value)", "Property management fees", "Rental agency fees", "Real estate consulting"],
    salary_range_africa: "Income is commission-based. One deal can earn ₦100,000–₦5,000,000+ depending on property value.",
    where_to_learn: ["Local real estate association training", "YouTube (Nigeria Real Estate, Ghana Property)", "PropertyPro agent resources"],
    common_mistakes: ["Not specializing in a location or property type", "Poor follow-up with leads", "No documented client agreement"],
    next_step: "Visit 5 properties in your area this week and practice describing each one's value proposition.",
  },
  {
    title: "Nurse",
    keywords: ["nurse", "nursing career", "registered nurse", "healthcare career", "nursing", "become a nurse"],
    overview: "Nurses provide patient care, administer treatment, monitor health conditions, and support doctors across hospitals, clinics, and community health settings.",
    responsibilities: ["Patient assessment and monitoring", "Administer medications and treatments", "Coordinate with doctors and other healthcare staff", "Educate patients and families", "Document patient records"],
    skills_required: ["Medical and clinical knowledge", "Compassion and empathy", "Attention to detail", "Communication", "Physical and emotional resilience"],
    tools_used: ["EHR systems (Electronic Health Records)", "Medical equipment", "Hospital management software"],
    how_to_start: ["Complete a nursing degree (BSN or diploma)", "Pass national licensing exams (NCLEX in US, NMC in UK, NMCN in Nigeria)", "Begin as a junior nurse", "Specialize after 2–3 years"],
    monetization_paths: ["Hospital and clinic employment", "Private nursing", "Travel nursing (very lucrative abroad)", "Health consulting"],
    salary_range_africa: "Nigeria: ₦80,000–₦250,000/month in public sector. Private and international: significantly higher. Abroad: $50,000–$100,000+/year.",
    where_to_learn: ["Nursing schools and universities", "NMCN (Nigeria)", "WHO nursing resources", "Khan Academy (nursing support)"],
    common_mistakes: ["Choosing nursing without understanding emotional demands", "Not pursuing specialization early enough", "Ignoring international licensing pathways"],
    next_step: "Research the nursing licensing body in your country and list the requirements to become registered.",
  },
  {
    title: "Lawyer",
    keywords: ["lawyer", "attorney", "legal career", "how to become a lawyer", "solicitor", "barrister"],
    overview: "Lawyers advise clients on legal matters and represent them in court or negotiations. Specializations include corporate law, criminal law, family law, and IP law.",
    responsibilities: ["Research and analyze legal issues", "Draft legal documents", "Represent clients in court", "Advise on compliance and risk", "Negotiate settlements"],
    skills_required: ["Legal research and writing", "Critical thinking", "Oral advocacy", "Negotiation", "Attention to detail"],
    tools_used: ["Westlaw or LexisNexis", "Microsoft Office", "Case management software", "Legal research databases"],
    how_to_start: ["Complete LLB degree", "Pass Bar exams (Nigerian Bar, Ghanaian Bar, South African Bar, etc.)", "Complete pupillage or internship", "Build experience in a firm", "Consider specialization"],
    monetization_paths: ["Law firm employment", "Solo practice", "In-house counsel for corporations", "Consulting and advisory"],
    salary_range_africa: "Entry: ₦80,000–₦200,000/month. Senior lawyer: ₦500,000–₦3,000,000+/month. Partner level: significantly higher.",
    where_to_learn: ["Law school (mandatory)", "Nigerian Law School", "Coursera Legal courses", "CLE programs"],
    common_mistakes: ["Weak written legal drafting skills", "Not specializing", "Ignoring networking — law is relationship-driven"],
    next_step: "Pick one area of law that interests you most and read one judgment from a court in that area this week.",
  },
  {
    title: "Agricultural Entrepreneur",
    keywords: ["farming", "agriculture business", "agribusiness", "agricultural entrepreneur", "crop farming", "poultry farming"],
    overview: "Agricultural entrepreneurs produce and sell food — crops, poultry, fish, dairy — using modern methods to improve yield and profitability. Africa's food demand creates enormous opportunity.",
    responsibilities: ["Plan and manage farm operations", "Apply modern agricultural techniques", "Manage staff and equipment", "Market and sell produce", "Manage finances and supply chains"],
    skills_required: ["Agronomy or animal husbandry knowledge", "Business management", "Financial planning", "Marketing", "Resilience (weather, market fluctuations)"],
    tools_used: ["Irrigation systems", "Farm management apps", "Paystack (payments)", "WhatsApp (market)", "Extension services"],
    how_to_start: ["Start small with one commodity (poultry, catfish, vegetables)", "Access free training from agricultural extension services", "Apply for government grants or agricultural loans (BOA, NIRSAL in Nigeria)", "Join a cooperative for market access and inputs"],
    monetization_paths: ["Direct sale to markets", "Supply to hotels and restaurants", "Agro-processing", "Export (premium pricing)", "Agricultural consulting"],
    salary_range_africa: "Highly variable. Small poultry farm: ₦100,000–₦500,000/month profit. Large-scale farming: millions monthly.",
    where_to_learn: ["Ministry of Agriculture programs", "Agropreneur Africa", "YouTube farming channels", "IITA (International Institute of Tropical Agriculture)"],
    common_mistakes: ["No market research before production", "No record keeping", "Depending solely on rain-fed agriculture"],
    next_step: "Identify one agricultural product in high demand in your local market and research the capital required to start at small scale.",
  },
  {
    title: "Translator / Interpreter",
    keywords: ["translator", "interpreter", "translation career", "language services", "localization"],
    overview: "Translators convert written content between languages; interpreters handle spoken language in real time. Both are in high demand globally and within Africa's multilingual context.",
    responsibilities: ["Translate documents accurately", "Interpret in meetings or events (interpreters)", "Maintain terminology consistency", "Research subject-specific vocabulary", "Meet turnaround deadlines"],
    skills_required: ["Fluency in at least two languages", "Excellent writing in target language", "Research ability", "Subject knowledge (legal, medical, technical)", "Confidentiality"],
    tools_used: ["SDL Trados", "memoQ", "Google Translate (for reference only)", "Microsoft Word", "Proz.com"],
    how_to_start: ["Identify language pairs with high demand (French-English, Arabic-English, Yoruba-English)", "Build a portfolio of translated samples", "Join Proz.com or TranslatorsCafe", "Specialize in legal, medical, or technical translation"],
    monetization_paths: ["Per word rates ($0.05–$0.20/word)", "Per hour interpretation fees", "Document translation packages", "Localization for tech companies"],
    salary_range_africa: "Part-time: ₦50,000–₦200,000/month. Full-time specialized: ₦300,000–₦800,000/month. UN and international org interpreters: very high.",
    where_to_learn: ["Coursera Translation courses", "ATA (American Translators Association) resources", "YouTube", "Practice through volunteer translation"],
    common_mistakes: ["Accepting work outside language competence", "No specialization — generalist approach", "Underestimating research time"],
    next_step: "Translate a 300-word article from your source language to your target language today and evaluate the quality honestly.",
  },
  {
    title: "Electrician (Solar Specialist)",
    keywords: ["solar installation", "solar energy", "solar technician", "solar electrician", "renewable energy technician"],
    overview: "Solar specialists install and maintain solar panel systems for homes, businesses, and communities. One of the fastest-growing trades in Africa due to power challenges.",
    responsibilities: ["Design solar systems (panel, inverter, battery sizing)", "Install solar panels and wiring", "Set up inverters and charge controllers", "Maintain and repair systems", "Educate clients on system use"],
    skills_required: ["Electrical fundamentals", "Solar system design", "Safe working practices", "Customer communication", "Problem diagnosis"],
    tools_used: ["Multimeter", "Solar design software (PVsyst, SolarEdge)", "Drill", "Cable crimpers", "Charge controllers", "Inverters"],
    how_to_start: ["Get basic electrical training first", "Take a solar installation course", "Get certified by NASENI, REA, or UNDP solar programs (Nigeria)", "Start with small residential systems", "Progress to industrial and commercial"],
    monetization_paths: ["Installation contracts", "Maintenance contracts", "System design consulting", "Reselling equipment"],
    salary_range_africa: "Residential installation: ₦100,000–₦500,000+ per job. Monthly income for active technicians: ₦200,000–₦700,000+.",
    where_to_learn: ["NASENI Training Centers", "UNDP Solar Energy Programs", "YouTube (solar installation guides)", "Renewable Energy Association training"],
    common_mistakes: ["Undersizing systems without proper load calculation", "Poor cable management", "No after-sales support"],
    next_step: "Watch a complete solar installation guide on YouTube this week and list the tools and components you would need.",
  },
  {
    title: "Customer Service Representative",
    keywords: ["customer service", "customer support", "call center", "customer experience", "crm"],
    overview: "Customer service representatives handle customer inquiries, complaints, and support requests — a foundational role in almost every industry that also leads to management and CX strategy careers.",
    responsibilities: ["Respond to customer inquiries", "Resolve complaints efficiently", "Document interactions in CRM", "Escalate complex issues", "Provide product information"],
    skills_required: ["Communication", "Patience and empathy", "Problem-solving", "Product knowledge", "CRM software"],
    tools_used: ["Zendesk", "Freshdesk", "Intercom", "HubSpot", "Slack", "Zoom"],
    how_to_start: ["Apply for entry-level customer service roles", "Learn one CRM tool (Zendesk has free training)", "Develop active listening skills", "Build toward team lead and CX manager roles"],
    monetization_paths: ["Employment (entry to senior)", "Freelance customer support for startups", "CX consulting"],
    salary_range_africa: "Entry: ₦60,000–₦150,000/month. Senior/Manager: ₦300,000–₦600,000/month. Remote for US/UK companies: $1,500–$3,500/month.",
    where_to_learn: ["Zendesk Training (free)", "HubSpot Academy (free)", "Coursera Customer Service courses"],
    common_mistakes: ["No active listening — interrupting customers", "Escalating too quickly without attempting resolution", "Poor documentation"],
    next_step: "Complete the free Zendesk Support training module today.",
  },
  {
    title: "Recruitment Consultant",
    keywords: ["recruitment consultant", "recruiter", "headhunter", "talent acquisition", "staffing", "recruitment career"],
    overview: "Recruitment consultants connect employers with the right candidates. They work for agencies or in-house HR teams and earn commissions on successful placements.",
    responsibilities: ["Source and screen candidates", "Build relationships with hiring companies", "Conduct interviews and assessments", "Negotiate offers", "Manage the end-to-end hiring process"],
    skills_required: ["Communication and persuasion", "People judgment", "Networking", "CRM and ATS tools", "Industry knowledge"],
    tools_used: ["LinkedIn Recruiter", "Workday", "Greenhouse", "Lever", "Zoho Recruit", "Breezy HR"],
    how_to_start: ["Start in an agency handling high-volume roles", "Build a strong LinkedIn profile", "Learn Boolean search for sourcing", "Specialize in a sector (tech, finance, healthcare)"],
    monetization_paths: ["Agency placement commissions (15–25% of first year salary)", "In-house recruiter employment", "Independent/executive search consultancy"],
    salary_range_africa: "Entry: ₦80,000–₦200,000/month base + commissions. Senior: ₦400,000–₦1,500,000+/month with commissions.",
    where_to_learn: ["LinkedIn Learning Recruitment courses", "CIPD (HR and recruitment)", "YouTube (recruiting strategies)", "RecruitingDaily.com"],
    common_mistakes: ["Not building long-term relationships — only transactional", "Poor candidate experience", "Specializing too broadly"],
    next_step: "Create a structured LinkedIn profile and connect with 5 hiring managers in your target industry this week.",
  },
  {
    title: "Machine Learning Engineer",
    keywords: ["machine learning engineer", "ml engineer", "ai engineer", "deep learning", "nlp engineer"],
    overview: "ML engineers build systems that learn from data to make predictions or automate tasks. They bridge data science and software engineering.",
    responsibilities: ["Build and train ML models", "Deploy models to production", "Monitor model performance", "Build ML pipelines", "Collaborate with data scientists"],
    skills_required: ["Python", "ML frameworks (TensorFlow, PyTorch)", "MLOps tools", "SQL", "Cloud platforms", "Software engineering fundamentals"],
    tools_used: ["Python", "TensorFlow", "PyTorch", "MLflow", "Airflow", "Docker", "AWS SageMaker", "Hugging Face"],
    how_to_start: ["Master Python and statistics first", "Complete fast.ai or Andrew Ng courses", "Build 3 end-to-end ML projects", "Learn MLOps and deployment", "Contribute to open source ML projects"],
    monetization_paths: ["Employed ML engineer", "Research roles", "Freelance AI consulting", "AI startup"],
    salary_range_africa: "Remote: $7,000–$20,000+/month. One of the highest-paid tech specializations globally.",
    where_to_learn: ["fast.ai (free)", "DeepLearning.ai", "CS229 Stanford (free)", "Kaggle", "Hugging Face Course (free)"],
    common_mistakes: ["No production experience — only research notebooks", "Ignoring software engineering best practices", "Models that work in Jupyter but fail in production"],
    next_step: "Complete lesson 1 of fast.ai this week and run your first image classification model.",
  },
];
